openapi: 3.0.3
info:
  title: Amicci Project Management API
  description: API para gerenciamento de projetos da Amicci
  version: 1.0.0

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
        email:
          type: string
          format: email
        name:
          type: string
        role:
          type: string
          enum: [admin, manager, user]
    
    Category:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
    
    Retailer:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        contact:
          type: string
        email:
          type: string
          format: email
        phone:
          type: string
    
    Product:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        specifications:
          type: string
        estimated_cost:
          type: number
          format: float
        status:
          type: string
          enum: [draft, in_progress, completed, cancelled]
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
    
    Project:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        description:
          type: string
        retailer:
          $ref: '#/components/schemas/Retailer'
        responsible:
          $ref: '#/components/schemas/User'
        category:
          $ref: '#/components/schemas/Category'
        launch_date:
          type: string
          format: date
        status:
          type: string
          enum: [draft, planning, in_progress, review, completed, cancelled]
        products:
          type: array
          items:
            $ref: '#/components/schemas/Product'
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time